version: "3"

services:
  techtalks.producer:
    image: nileshgule/techtalksproducer:rabbitmq-keda-5.0
    build:
      context: src
      dockerfile: Dockerfile-TechTalksMQProducer

  techtalks.consumer:
    image: nileshgule/techtalksconsumer:rabbitmq-keda-5.0
    build:
      context: src
      dockerfile: Dockerfile-TechTalksMQConsumer
