#Create this file from command line kubectl create secret generic regcred --from-file=/home/your user/.docker/config.json
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: Opaque
data:
  config.json: 
